name: Deploy Sistema Turnos AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: sistema-turnos-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir imagen Docker
        run: docker build -t $ECR_REPOSITORY ./backend

      - name: Etiquetar imagen
        run: docker tag $ECR_REPOSITORY:latest 851725347003.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Subir imagen a ECR
        run: docker push 851725347003.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:latest